# Generated by Django 4.2.11 on 2024-03-19 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud_launchpad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aws_access_key', models.CharField(max_length=50)),
                ('aws_secret_key', models.CharField(max_length=100)),
                ('server_type', models.CharField(max_length=20)),
                ('container_type', models.CharField(max_length=20)),
                ('cluster_name', models.CharField(max_length=50)),
                ('node_group_name', models.CharField(max_length=50)),
                ('container_name', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('ecr_repo_name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('github_token', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=50)),
                ('repo_owner_name', models.CharField(max_length=50)),
                ('project_technology', models.CharField(max_length=20)),
                ('technology_version', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=20)),
                ('libraries', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
