# Generated by Django 4.2.11 on 2024-03-26 11:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=10)),
                ('is_active', models.BooleanField()),
                ('is_super_admin', models.BooleanField(blank=True)),
                ('is_company_admin', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'user_master',
            },
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_launchpad.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_launchpad.usermaster')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.CharField(max_length=200)),
                ('browser', models.CharField(max_length=200)),
                ('login_date_time', models.DateTimeField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_launchpad.usermaster')),
            ],
            options={
                'db_table': 'user_login_history',
            },
        ),
    ]
