# Generated by Django 4.2.11 on 2024-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0003_role_usermaster_alter_userdetails_id_userrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_company_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_super_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
