# Generated by Django 4.2.11 on 2024-03-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0004_alter_usermaster_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('repo_owner_name', models.CharField(max_length=100)),
                ('cluster_name', models.CharField(max_length=100)),
                ('container_type', models.CharField(max_length=100)),
                ('node_group_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_launchpad.usermaster')),
            ],
            options={
                'db_table': 'project_master',
            },
        ),
        migrations.CreateModel(
            name='ProjectCredDetails',
            fields=[
                ('project_cred_id', models.AutoField(primary_key=True, serialize=False)),
                ('aws_access_key', models.CharField(max_length=200)),
                ('aws_secret_key', models.CharField(max_length=200)),
                ('github_token', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_launchpad.projectmaster')),
            ],
            options={
                'db_table': 'project_cred_details',
            },
        ),
        migrations.CreateModel(
            name='MicroservicesDetails',
            fields=[
                ('pm_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('ecr_repo_name', models.CharField(max_length=100)),
                ('container_name', models.CharField(max_length=100)),
                ('project_technology', models.CharField(max_length=100)),
                ('technology_version', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('technology_type', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_launchpad.projectmaster')),
            ],
            options={
                'db_table': 'microservices_details',
            },
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_launchpad.usermaster')),
            ],
            options={
                'db_table': 'company_master',
            },
        ),
    ]
