# Generated by Django 4.2.11 on 2024-03-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0005_alter_usermaster_email_projectmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAdminDetail',
            fields=[
                ('company_admin_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_launchpad.companymaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_launchpad.usermaster')),
            ],
            options={
                'db_table': 'company_admin_detail',
            },
        ),
    ]
