# Generated by Django 4.2.11 on 2024-03-28 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0006_companyadmindetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='created_by',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='updated_by',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
