# Generated by Django 4.2.11 on 2024-03-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0007_usermaster_created_by_usermaster_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='created_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
