# Generated by Django 4.2.11 on 2024-03-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0008_alter_usermaster_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
