# Generated by Django 4.2.11 on 2024-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0009_alter_usermaster_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymaster',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectmaster',
            name='user',
        ),
        migrations.AddField(
            model_name='companymaster',
            name='created_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='updated_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='microservicesdetails',
            name='created_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='microservicesdetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='microservicesdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='microservicesdetails',
            name='updated_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='microservicesdetails',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='created_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='updated_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
