# Generated by Django 4.2.11 on 2024-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0010_remove_companymaster_user_remove_projectmaster_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microservicesdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
