# Generated by Django 4.2.11 on 2024-03-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0011_companymaster_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='microservicesdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='microservicesdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='cloud_launchpad.usermaster'),
        ),
    ]
