# Generated by Django 4.2.11 on 2024-03-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0012_alter_companymaster_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to='cloud_launchpad.usermaster'),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_user', to='cloud_launchpad.usermaster'),
        ),
    ]
