# Generated by Django 4.2.11 on 2024-04-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0014_microservicesdetails_container_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcreddetails',
            name='github_token',
            field=models.CharField(max_length=256),
        ),
    ]
