# Generated by Django 4.2.11 on 2024-04-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_launchpad', '0015_alter_projectcreddetails_github_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
